" mark/palettes.vim: Additional palettes for mark highlighting.
"
" DEPENDENCIES:
"
" Copyright: (C) 2012-2026 Ingo Karkat
"   The VIM LICENSE applies to this script; see ':help copyright'.
"
" Maintainer:	Ingo Karkat <ingo@karkat.de>
" Contributors: rockybalboa4, sfinktah
"
" Version:     3.4.1

function! mark#palettes#Extended()
	return [
		\   { 'ctermbg':'Blue',       'ctermfg':'Black', 'guibg':'#A1B7FF', 'guifg':'#001E80' },
		\   { 'ctermbg':'Magenta',    'ctermfg':'Black', 'guibg':'#FFA1C6', 'guifg':'#80005D' },
		\   { 'ctermbg':'Green',      'ctermfg':'Black', 'guibg':'#ACFFA1', 'guifg':'#0F8000' },
		\   { 'ctermbg':'Yellow',     'ctermfg':'Black', 'guibg':'#FFE8A1', 'guifg':'#806000' },
		\   { 'ctermbg':'DarkCyan',   'ctermfg':'Black', 'guibg':'#D2A1FF', 'guifg':'#420080' },
		\   { 'ctermbg':'Cyan',       'ctermfg':'Black', 'guibg':'#A1FEFF', 'guifg':'#007F80' },
		\   { 'ctermbg':'DarkBlue',   'ctermfg':'Black', 'guibg':'#A1DBFF', 'guifg':'#004E80' },
		\   { 'ctermbg':'DarkMagenta','ctermfg':'Black', 'guibg':'#A29CCF', 'guifg':'#120080' },
		\   { 'ctermbg':'DarkRed',    'ctermfg':'Black', 'guibg':'#F5A1FF', 'guifg':'#720080' },
		\   { 'ctermbg':'Brown',      'ctermfg':'Black', 'guibg':'#FFC4A1', 'guifg':'#803000' },
		\   { 'ctermbg':'DarkGreen',  'ctermfg':'Black', 'guibg':'#D0FFA1', 'guifg':'#3F8000' },
		\   { 'ctermbg':'Red',        'ctermfg':'Black', 'guibg':'#F3FFA1', 'guifg':'#6F8000' },
		\   { 'ctermbg':'White',      'ctermfg':'Gray',  'guibg':'#E3E3D2', 'guifg':'#999999' },
		\   { 'ctermbg':'LightGray',  'ctermfg':'White', 'guibg':'#D3D3C3', 'guifg':'#666666' },
		\   { 'ctermbg':'Gray',       'ctermfg':'Black', 'guibg':'#A3A396', 'guifg':'#222222' },
		\   { 'ctermbg':'Black',      'ctermfg':'White', 'guibg':'#53534C', 'guifg':'#DDDDDD' },
		\   { 'ctermbg':'Black',      'ctermfg':'Gray',  'guibg':'#131311', 'guifg':'#AAAAAA' },
		\   { 'ctermbg':'Blue',       'ctermfg':'White', 'guibg':'#0000FF', 'guifg':'#F0F0FF' },
		\   { 'ctermbg':'DarkRed',    'ctermfg':'White', 'guibg':'#FF0000', 'guifg':'#FFFFFF' },
		\   { 'ctermbg':'DarkGreen',  'ctermfg':'White', 'guibg':'#00FF00', 'guifg':'#355F35' },
		\   { 'ctermbg':'DarkYellow', 'ctermfg':'White', 'guibg':'#FFFF00', 'guifg':'#6F6F4C' },
		\]
endfunction

function! mark#palettes#Soft()
	return [
		\   {                                            'guibg':'#d1dbff', 'guifg':'#001250' },
		\   {                                            'guibg':'#ffd1e2', 'guifg':'#500039' },
		\   {                                            'guibg':'#d6ffd1', 'guifg':'#095000' },
		\   {                                            'guibg':'#fff3d1', 'guifg':'#503c00' },
		\   {                                            'guibg':'#e8d1ff', 'guifg':'#280050' },
		\   {                                            'guibg':'#d1feff', 'guifg':'#004e50' },
		\   {                                            'guibg':'#d1edff', 'guifg':'#003050' },
		\   {                                            'guibg':'#d6d1ff', 'guifg':'#0a0050' },
		\   {                                            'guibg':'#f9d1ff', 'guifg':'#460050' },
		\   {                                            'guibg':'#ffe1d1', 'guifg':'#501d00' },
		\   {                                            'guibg':'#e8ffd1', 'guifg':'#265000' },
		\   {                                            'guibg':'#f8ffd1', 'guifg':'#455000' },
		\   {                                            'guibg':'#f8f8f8', 'guifg':'#101010' },
		\   {                                            'guibg':'#f0f0f0', 'guifg':'#202020' },
		\   {                                            'guibg':'#e8e8e8', 'guifg':'#303030' },
		\   {                                            'guibg':'#d8d8d8', 'guifg':'#404040' },
		\   {                                            'guibg':'#c8c8c8', 'guifg':'#505050' },
		\   {                                            'guibg':'#b0b0ff', 'guifg':'#4c4c6f' },
		\   {                                            'guibg':'#ffb0b0', 'guifg':'#5f4141' },
		\   {                                            'guibg':'#b0ffb0', 'guifg':'#415f41' },
		\   {                                            'guibg':'#ffff80', 'guifg':'#4f4f27' },
		\]
endfunction
function! mark#palettes#Softer()
	return [
		\   {                                            'guibg':'#e9edff', 'guifg':'#001250' },
		\   {                                            'guibg':'#ffe9f1', 'guifg':'#500039' },
		\   {                                            'guibg':'#ebffe9', 'guifg':'#095000' },
		\   {                                            'guibg':'#fff9e9', 'guifg':'#503c00' },
		\   {                                            'guibg':'#f4e9ff', 'guifg':'#280050' },
		\   {                                            'guibg':'#e9feff', 'guifg':'#004e50' },
		\   {                                            'guibg':'#e9f6ff', 'guifg':'#003050' },
		\   {                                            'guibg':'#ebe9ff', 'guifg':'#0a0050' },
		\   {                                            'guibg':'#fce9ff', 'guifg':'#460050' },
		\   {                                            'guibg':'#fff0e9', 'guifg':'#501d00' },
		\   {                                            'guibg':'#f4ffe9', 'guifg':'#265000' },
		\   {                                            'guibg':'#fbffe9', 'guifg':'#455000' },
		\   {                                            'guibg':'#f8f8f8', 'guifg':'#101010' },
		\   {                                            'guibg':'#f2f2f2', 'guifg':'#202020' },
		\   {                                            'guibg':'#ececec', 'guifg':'#303030' },
		\   {                                            'guibg':'#e3e3e3', 'guifg':'#404040' },
		\   {                                            'guibg':'#dcdcdc', 'guifg':'#505050' },
		\   {                                            'guibg':'#c8c8ff', 'guifg':'#4c4c6f' },
		\   {                                            'guibg':'#ffc8c8', 'guifg':'#5f4141' },
		\   {                                            'guibg':'#c8ffc8', 'guifg':'#415f41' },
		\   {                                            'guibg':'#ffff98', 'guifg':'#4f4f27' },
		\]
endfunction

function! mark#palettes#Maximum()
		let l:palette = [
		\   { 'ctermbg':'Cyan',       'ctermfg':'Black', 'guibg':'#8ccbea', 'guifg':'Black' },
		\   { 'ctermbg':'Green',      'ctermfg':'Black', 'guibg':'#a4e57e', 'guifg':'Black' },
		\   { 'ctermbg':'Yellow',     'ctermfg':'Black', 'guibg':'#ffdb72', 'guifg':'Black' },
		\   { 'ctermbg':'Red',        'ctermfg':'Black', 'guibg':'#ff7272', 'guifg':'Black' },
		\   { 'ctermbg':'Magenta',    'ctermfg':'Black', 'guibg':'#ffb3ff', 'guifg':'Black' },
		\   { 'ctermbg':'Blue',       'ctermfg':'Black', 'guibg':'#9999ff', 'guifg':'Black' },
		\]
		if has('gui_running') || &t_Co >= 88
		let l:palette += [
		\   { 'ctermfg':'White',      'ctermbg':'17',    'guifg':'White',   'guibg':'#00005f' },
		\   { 'ctermfg':'White',      'ctermbg':'22',    'guifg':'White',   'guibg':'#005f00' },
		\   { 'ctermfg':'White',      'ctermbg':'23',    'guifg':'White',   'guibg':'#005f5f' },
		\   { 'ctermfg':'White',      'ctermbg':'27',    'guifg':'White',   'guibg':'#005fff' },
		\   { 'ctermfg':'White',      'ctermbg':'29',    'guifg':'White',   'guibg':'#00875f' },
		\   { 'ctermfg':'White',      'ctermbg':'34',    'guifg':'White',   'guibg':'#00af00' },
		\   { 'ctermfg':'Black',      'ctermbg':'37',    'guifg':'Black',   'guibg':'#00afaf' },
		\   { 'ctermfg':'Black',      'ctermbg':'43',    'guifg':'Black',   'guibg':'#00d7af' },
		\   { 'ctermfg':'Black',      'ctermbg':'47',    'guifg':'Black',   'guibg':'#00ff5f' },
		\   { 'ctermfg':'White',      'ctermbg':'52',    'guifg':'White',   'guibg':'#5f0000' },
		\   { 'ctermfg':'White',      'ctermbg':'53',    'guifg':'White',   'guibg':'#5f005f' },
		\   { 'ctermfg':'White',      'ctermbg':'58',    'guifg':'White',   'guibg':'#5f5f00' },
		\   { 'ctermfg':'White',      'ctermbg':'60',    'guifg':'White',   'guibg':'#5f5f87' },
		\   { 'ctermfg':'White',      'ctermbg':'64',    'guifg':'White',   'guibg':'#5f8700' },
		\   { 'ctermfg':'White',      'ctermbg':'65',    'guifg':'White',   'guibg':'#5f875f' },
		\   { 'ctermfg':'Black',      'ctermbg':'66',    'guifg':'Black',   'guibg':'#5f8787' },
		\   { 'ctermfg':'Black',      'ctermbg':'72',    'guifg':'Black',   'guibg':'#5faf87' },
		\   { 'ctermfg':'Black',      'ctermbg':'74',    'guifg':'Black',   'guibg':'#5fafd7' },
		\   { 'ctermfg':'Black',      'ctermbg':'78',    'guifg':'Black',   'guibg':'#5fd787' },
		\   { 'ctermfg':'Black',      'ctermbg':'79',    'guifg':'Black',   'guibg':'#5fd7af' },
		\   { 'ctermfg':'Black',      'ctermbg':'85',    'guifg':'Black',   'guibg':'#5fffaf' },
		\]
		endif
		if has('gui_running') || &t_Co >= 256
		let l:palette += [
		\   { 'ctermfg':'White',      'ctermbg':'90',    'guifg':'White',   'guibg':'#870087' },
		\   { 'ctermfg':'White',      'ctermbg':'95',    'guifg':'White',   'guibg':'#875f5f' },
		\   { 'ctermfg':'White',      'ctermbg':'96',    'guifg':'White',   'guibg':'#875f87' },
		\   { 'ctermfg':'Black',      'ctermbg':'101',   'guifg':'Black',   'guibg':'#87875f' },
		\   { 'ctermfg':'Black',      'ctermbg':'107',   'guifg':'Black',   'guibg':'#87af5f' },
		\   { 'ctermfg':'Black',      'ctermbg':'114',   'guifg':'Black',   'guibg':'#87d787' },
		\   { 'ctermfg':'Black',      'ctermbg':'117',   'guifg':'Black',   'guibg':'#87d7ff' },
		\   { 'ctermfg':'Black',      'ctermbg':'118',   'guifg':'Black',   'guibg':'#87ff00' },
		\   { 'ctermfg':'Black',      'ctermbg':'122',   'guifg':'Black',   'guibg':'#87ffd7' },
		\   { 'ctermfg':'White',      'ctermbg':'130',   'guifg':'White',   'guibg':'#af5f00' },
		\   { 'ctermfg':'White',      'ctermbg':'131',   'guifg':'White',   'guibg':'#af5f5f' },
		\   { 'ctermfg':'Black',      'ctermbg':'133',   'guifg':'Black',   'guibg':'#af5faf' },
		\   { 'ctermfg':'Black',      'ctermbg':'138',   'guifg':'Black',   'guibg':'#af8787' },
		\   { 'ctermfg':'Black',      'ctermbg':'142',   'guifg':'Black',   'guibg':'#afaf00' },
		\   { 'ctermfg':'Black',      'ctermbg':'152',   'guifg':'Black',   'guibg':'#afd7d7' },
		\   { 'ctermfg':'White',      'ctermbg':'160',   'guifg':'White',   'guibg':'#d70000' },
		\   { 'ctermfg':'Black',      'ctermbg':'166',   'guifg':'Black',   'guibg':'#d75f00' },
		\   { 'ctermfg':'Black',      'ctermbg':'169',   'guifg':'Black',   'guibg':'#d75faf' },
		\   { 'ctermfg':'Black',      'ctermbg':'174',   'guifg':'Black',   'guibg':'#d78787' },
		\   { 'ctermfg':'Black',      'ctermbg':'175',   'guifg':'Black',   'guibg':'#d787af' },
		\   { 'ctermfg':'Black',      'ctermbg':'186',   'guifg':'Black',   'guibg':'#d7d787' },
		\   { 'ctermfg':'Black',      'ctermbg':'190',   'guifg':'Black',   'guibg':'#d7ff00' },
		\   { 'ctermfg':'White',      'ctermbg':'198',   'guifg':'White',   'guibg':'#ff0087' },
		\   { 'ctermfg':'Black',      'ctermbg':'202',   'guifg':'Black',   'guibg':'#ff5f00' },
		\   { 'ctermfg':'Black',      'ctermbg':'204',   'guifg':'Black',   'guibg':'#ff5f87' },
		\   { 'ctermfg':'Black',      'ctermbg':'209',   'guifg':'Black',   'guibg':'#ff875f' },
		\   { 'ctermfg':'Black',      'ctermbg':'212',   'guifg':'Black',   'guibg':'#ff87d7' },
		\   { 'ctermfg':'Black',      'ctermbg':'215',   'guifg':'Black',   'guibg':'#ffaf5f' },
		\   { 'ctermfg':'Black',      'ctermbg':'220',   'guifg':'Black',   'guibg':'#ffd700' },
		\   { 'ctermfg':'Black',      'ctermbg':'224',   'guifg':'Black',   'guibg':'#ffd7d7' },
		\   { 'ctermfg':'Black',      'ctermbg':'228',   'guifg':'Black',   'guibg':'#ffff87' },
		\]
		endif
		if has('gui_running')
		let l:palette += [
		\   {                                            'guifg':'Black',   'guibg':'#b3dcff' },
		\   {                                            'guifg':'Black',   'guibg':'#99cbd6' },
		\   {                                            'guifg':'Black',   'guibg':'#7afff0' },
		\   {                                            'guifg':'Black',   'guibg':'#a6ffd2' },
		\   {                                            'guifg':'Black',   'guibg':'#a2de9e' },
		\   {                                            'guifg':'Black',   'guibg':'#bcff80' },
		\   {                                            'guifg':'Black',   'guibg':'#e7ff8c' },
		\   {                                            'guifg':'Black',   'guibg':'#f2e19d' },
		\   {                                            'guifg':'Black',   'guibg':'#ffcc73' },
		\   {                                            'guifg':'Black',   'guibg':'#f7af83' },
		\   {                                            'guifg':'Black',   'guibg':'#fcb9b1' },
		\   {                                            'guifg':'Black',   'guibg':'#ff8092' },
		\   {                                            'guifg':'Black',   'guibg':'#ff73bb' },
		\   {                                            'guifg':'Black',   'guibg':'#fc97ef' },
		\   {                                            'guifg':'Black',   'guibg':'#c8a3d9' },
		\   {                                            'guifg':'Black',   'guibg':'#ac98eb' },
		\   {                                            'guifg':'Black',   'guibg':'#6a6feb' },
		\   {                                            'guifg':'Black',   'guibg':'#8caeff' },
		\   {                                            'guifg':'Black',   'guibg':'#70b9fa' },
		\]
		endif
	return l:palette
endfunction

function! mark#palettes#FiftyFive()
	return [
		\   { 'ctermbg':'31',  'ctermfg':'Black', 'guibg':'#8CCBEA', 'guifg':'Black' },
		\   { 'ctermbg':'35',  'ctermfg':'Black', 'guibg':'#A4E57E', 'guifg':'Black' },
		\   { 'ctermbg':'39',  'ctermfg':'Black', 'guibg':'#FFDB72', 'guifg':'Black' },
		\   { 'ctermbg':'43',  'ctermfg':'Black', 'guibg':'#FF7272', 'guifg':'Black' },
		\   { 'ctermbg':'47',  'ctermfg':'Black', 'guibg':'#FFB3FF', 'guifg':'Black' },
		\   { 'ctermbg':'51',  'ctermfg':'Black', 'guibg':'#9999FF', 'guifg':'Black' },
		\   { 'ctermbg':'55',  'ctermfg':'Black', 'guibg':'#ff4848', 'guifg':'Black' },
		\   { 'ctermbg':'59',  'ctermfg':'White', 'guibg':'#ae202c', 'guifg':'White' },
		\   { 'ctermbg':'63',  'ctermfg':'Black', 'guibg':'#eed3d5', 'guifg':'Black' },
		\   { 'ctermbg':'119', 'ctermfg':'White', 'guibg':'#20ae2c', 'guifg':'White' },
		\   { 'ctermbg':'195', 'ctermfg':'Black', 'guibg':'#72FFF2', 'guifg':'Black' },
		\   { 'ctermbg':'175', 'ctermfg':'Black', 'guibg':'#79f694', 'guifg':'Black' },
		\   { 'ctermbg':'163', 'ctermfg':'Black', 'guibg':'#FFFFB3', 'guifg':'Black' },
		\   { 'ctermbg':'235', 'ctermfg':'Black', 'guibg':'#ffd599', 'guifg':'Black' },
		\   { 'ctermbg':'143', 'ctermfg':'Black', 'guibg':'#91f3c7', 'guifg':'Black' },
		\   { 'ctermbg':'147', 'ctermfg':'Black', 'guibg':'#F2FF72', 'guifg':'Black' },
		\   { 'ctermbg':'139', 'ctermfg':'Black', 'guibg':'#ffd6fd', 'guifg':'Black' },
		\   { 'ctermbg':'223', 'ctermfg':'Black', 'guibg':'#d5d3ee', 'guifg':'Black' },
		\   { 'ctermbg':'83',  'ctermfg':'Black', 'guibg':'#f391c7', 'guifg':'Black' },
		\   { 'ctermbg':'95',  'ctermfg':'Black', 'guibg':'#CB8CEA', 'guifg':'Black' },
		\   { 'ctermbg':'91',  'ctermfg':'Black', 'guibg':'#888888', 'guifg':'Black' },
		\   { 'ctermbg':'159', 'ctermfg':'Black', 'guibg':'#72FFDB', 'guifg':'Black' },
		\   { 'ctermbg':'71',  'ctermfg':'Black', 'guibg':'#ffdb99', 'guifg':'Black' },
		\   { 'ctermbg':'67',  'ctermfg':'Black', 'guibg':'#f69479', 'guifg':'Black' },
		\   { 'ctermbg':'151', 'ctermfg':'Black', 'guibg':'#EA8CCB', 'guifg':'Black' },
		\   { 'ctermbg':'135', 'ctermfg':'Black', 'guibg':'#d599ff', 'guifg':'Black' },
		\   { 'ctermbg':'239', 'ctermfg':'Black', 'guibg':'#fdffd6', 'guifg':'Black' },
		\   { 'ctermbg':'107', 'ctermfg':'Black', 'guibg':'#72FF72', 'guifg':'Black' },
		\   { 'ctermbg':'155', 'ctermfg':'Black', 'guibg':'#7EA4E5', 'guifg':'Black' },
		\   { 'ctermbg':'99',  'ctermfg':'Black', 'guibg':'#E5A47E', 'guifg':'Black' },
		\   { 'ctermbg':'179', 'ctermfg':'Black', 'guibg':'#99ffdb', 'guifg':'Black' },
		\   { 'ctermbg':'127', 'ctermfg':'Black', 'guibg':'#94f679', 'guifg':'Black' },
		\   { 'ctermbg':'211', 'ctermfg':'Black', 'guibg':'#7272FF', 'guifg':'Black' },
		\   { 'ctermbg':'199', 'ctermfg':'Black', 'guibg':'#EACB8C', 'guifg':'Black' },
		\   { 'ctermbg':'187', 'ctermfg':'Black', 'guibg':'#fdd6ff', 'guifg':'Black' },
		\   { 'ctermbg':'171', 'ctermfg':'Black', 'guibg':'#d5eed3', 'guifg':'Black' },
		\   { 'ctermbg':'231', 'ctermfg':'Black', 'guibg':'#99dbff', 'guifg':'Black' },
		\   { 'ctermbg':'75',  'ctermfg':'Black', 'guibg':'#99d5ff', 'guifg':'Black' },
		\   { 'ctermbg':'247', 'ctermfg':'Black', 'guibg':'#72F2FF', 'guifg':'Black' },
		\   { 'ctermbg':'191', 'ctermfg':'Black', 'guibg':'#c7f391', 'guifg':'Black' },
		\   { 'ctermbg':'215', 'ctermfg':'White', 'guibg':'#4848ff', 'guifg':'White' },
		\   { 'ctermbg':'167', 'ctermfg':'White', 'guibg':'#2cae20', 'guifg':'White' },
		\   { 'ctermbg':'219', 'ctermfg':'White', 'guibg':'#2c20ae', 'guifg':'White' },
		\   { 'ctermbg':'183', 'ctermfg':'Black', 'guibg':'#ff99d5', 'guifg':'Black' },
		\   { 'ctermbg':'203', 'ctermfg':'Black', 'guibg':'#7EE5A4', 'guifg':'Black' },
		\   { 'ctermbg':'207', 'ctermfg':'Black', 'guibg':'#72DBFF', 'guifg':'Black' },
		\   { 'ctermbg':'243', 'ctermfg':'Black', 'guibg':'#c791f3', 'guifg':'Black' },
		\   { 'ctermbg':'227', 'ctermfg':'Black', 'guibg':'#7994f6', 'guifg':'Black' },
		\   { 'ctermbg':'103', 'ctermfg':'Black', 'guibg':'#DBFF72', 'guifg':'Black' },
		\   { 'ctermbg':'79',  'ctermfg':'Black', 'guibg':'#d6fffd', 'guifg':'Black' },
		\   { 'ctermbg':'123', 'ctermfg':'Black', 'guibg':'#d3eed5', 'guifg':'Black' },
		\   { 'ctermbg':'111', 'ctermfg':'Black', 'guibg':'#B3FFFF', 'guifg':'Black' },
		\   { 'ctermbg':'87',  'ctermfg':'Black', 'guibg':'#FFF272', 'guifg':'Black' },
		\   { 'ctermbg':'131', 'ctermfg':'Black', 'guibg':'#dbff99', 'guifg':'Black' },
		\   { 'ctermbg':'115', 'ctermfg':'Black', 'guibg':'#48ff48', 'guifg':'Black' },
		\]
endfunction

function! mark#palettes#Rainbow()
		let l:palette = [
		\   { 'co': 88,     'ctermfg':'White',      'ctermbg':'52',    'guifg':'White',   'guibg':'#5f0000' },
		\   { 'co': 256,    'ctermfg':'White',      'ctermbg':'160',   'guifg':'White',   'guibg':'#d70000' },
		\   { 'co': 16,     'ctermbg':'Red',        'ctermfg':'Black', 'guibg':'#ff7272', 'guifg':'Black' },
		\   { 'co': 16777216,                                          'guifg':'Black',   'guibg':'#fcb9b1' },
		\   { 'co': 256,    'ctermfg':'Black',      'ctermbg':'224',   'guifg':'Black',   'guibg':'#ffd7d7' },
		\   { 'co': 256,    'ctermfg':'Black',      'ctermbg':'202',   'guifg':'Black',   'guibg':'#ff5f00' },
		\   { 'co': 256,    'ctermfg':'White',      'ctermbg':'130',   'guifg':'White',   'guibg':'#af5f00' },
		\   { 'co': 256,    'ctermfg':'Black',      'ctermbg':'166',   'guifg':'Black',   'guibg':'#d75f00' },
		\   { 'co': 256,    'ctermfg':'Black',      'ctermbg':'209',   'guifg':'Black',   'guibg':'#ff875f' },
		\   { 'co': 16777216,                                          'guifg':'Black',   'guibg':'#f7af83' },
		\   { 'co': 256,    'ctermfg':'Black',      'ctermbg':'215',   'guifg':'Black',   'guibg':'#ffaf5f' },
		\   { 'co': 16777216,                                          'guifg':'Black',   'guibg':'#ffcc73' },
		\   { 'co': 256,    'ctermfg':'Black',      'ctermbg':'220',   'guifg':'Black',   'guibg':'#ffd700' },
		\   { 'co': 16,     'ctermbg':'Yellow',     'ctermfg':'Black', 'guibg':'#ffdb72', 'guifg':'Black' },
		\   { 'co': 16777216,                                          'guifg':'Black',   'guibg':'#f2e19d' },
		\   { 'co': 256,    'ctermfg':'Black',      'ctermbg':'186',   'guifg':'Black',   'guibg':'#d7d787' },
		\   { 'co': 256,    'ctermfg':'Black',      'ctermbg':'101',   'guifg':'Black',   'guibg':'#87875f' },
		\   { 'co': 88,     'ctermfg':'White',      'ctermbg':'58',    'guifg':'White',   'guibg':'#5f5f00' },
		\   { 'co': 256,    'ctermfg':'Black',      'ctermbg':'142',   'guifg':'Black',   'guibg':'#afaf00' },
		\   { 'co': 256,    'ctermfg':'Black',      'ctermbg':'228',   'guifg':'Black',   'guibg':'#ffff87' },
		\   { 'co': 16777216,                                          'guifg':'Black',   'guibg':'#e7ff8c' },
		\   { 'co': 256,    'ctermfg':'Black',      'ctermbg':'190',   'guifg':'Black',   'guibg':'#d7ff00' },
		\   { 'co': 256,    'ctermfg':'Black',      'ctermbg':'118',   'guifg':'Black',   'guibg':'#87ff00' },
		\   { 'co': 16777216,                                          'guifg':'Black',   'guibg':'#bcff80' },
		\   { 'co': 16,     'ctermbg':'Green',      'ctermfg':'Black', 'guibg':'#a4e57e', 'guifg':'Black' },
		\   { 'co': 16777216,                                          'guifg':'Black',   'guibg':'#a2de9e' },
		\   { 'co': 88,     'ctermfg':'White',      'ctermbg':'34',    'guifg':'White',   'guibg':'#00af00' },
		\   { 'co': 88,     'ctermfg':'White',      'ctermbg':'22',    'guifg':'White',   'guibg':'#005f00' },
		\   { 'co': 88,     'ctermfg':'White',      'ctermbg':'64',    'guifg':'White',   'guibg':'#5f8700' },
		\   { 'co': 256,    'ctermfg':'Black',      'ctermbg':'107',   'guifg':'Black',   'guibg':'#87af5f' },
		\   { 'co': 256,    'ctermfg':'Black',      'ctermbg':'114',   'guifg':'Black',   'guibg':'#87d787' },
		\   { 'co': 88,     'ctermfg':'Black',      'ctermbg':'78',    'guifg':'Black',   'guibg':'#5fd787' },
		\   { 'co': 88,     'ctermfg':'Black',      'ctermbg':'47',    'guifg':'Black',   'guibg':'#00ff5f' },
		\   { 'co': 88,     'ctermfg':'White',      'ctermbg':'65',    'guifg':'White',   'guibg':'#5f875f' },
		\   { 'co': 88,     'ctermfg':'Black',      'ctermbg':'66',    'guifg':'Black',   'guibg':'#5f8787' },
		\   { 'co': 88,     'ctermfg':'White',      'ctermbg':'29',    'guifg':'White',   'guibg':'#00875f' },
		\   { 'co': 88,     'ctermfg':'Black',      'ctermbg':'72',    'guifg':'Black',   'guibg':'#5faf87' },
		\   { 'co': 88,     'ctermfg':'Black',      'ctermbg':'85',    'guifg':'Black',   'guibg':'#5fffaf' },
		\   { 'co': 88,     'ctermfg':'Black',      'ctermbg':'43',    'guifg':'Black',   'guibg':'#00d7af' },
		\   { 'co': 88,     'ctermfg':'Black',      'ctermbg':'79',    'guifg':'Black',   'guibg':'#5fd7af' },
		\   { 'co': 256,    'ctermfg':'Black',      'ctermbg':'122',   'guifg':'Black',   'guibg':'#87ffd7' },
		\   { 'co': 16777216,                                          'guifg':'Black',   'guibg':'#a6ffd2' },
		\   { 'co': 16777216,                                          'guifg':'Black',   'guibg':'#7afff0' },
		\   { 'co': 88,     'ctermfg':'White',      'ctermbg':'23',    'guifg':'White',   'guibg':'#005f5f' },
		\   { 'co': 88,     'ctermfg':'Black',      'ctermbg':'37',    'guifg':'Black',   'guibg':'#00afaf' },
		\   { 'co': 256,    'ctermfg':'Black',      'ctermbg':'152',   'guifg':'Black',   'guibg':'#afd7d7' },
		\   { 'co': 16777216,                                          'guifg':'Black',   'guibg':'#99cbd6' },
		\   { 'co': 16,     'ctermbg':'Cyan',       'ctermfg':'Black', 'guibg':'#8ccbea', 'guifg':'Black' },
		\   { 'co': 16777216,                                          'guifg':'Black',   'guibg':'#70b9fa' },
		\   { 'co': 88,     'ctermfg':'Black',      'ctermbg':'74',    'guifg':'Black',   'guibg':'#5fafd7' },
		\   { 'co': 16777216,                                          'guifg':'Black',   'guibg':'#b3dcff' },
		\   { 'co': 256,    'ctermfg':'Black',      'ctermbg':'117',   'guifg':'Black',   'guibg':'#87d7ff' },
		\   { 'co': 16777216,                                          'guifg':'Black',   'guibg':'#8caeff' },
		\   { 'co': 16,     'ctermbg':'Blue',       'ctermfg':'Black', 'guibg':'#9999ff', 'guifg':'Black' },
		\   { 'co': 88,     'ctermfg':'White',      'ctermbg':'27',    'guifg':'White',   'guibg':'#005fff' },
		\   { 'co': 88,     'ctermfg':'White',      'ctermbg':'17',    'guifg':'White',   'guibg':'#00005f' },
		\   { 'co': 16777216,                                          'guifg':'Black',   'guibg':'#6a6feb' },
		\   { 'co': 16777216,                                          'guifg':'Black',   'guibg':'#ac98eb' },
		\   { 'co': 88,     'ctermfg':'White',      'ctermbg':'60',    'guifg':'White',   'guibg':'#5f5f87' },
		\   { 'co': 88,     'ctermfg':'White',      'ctermbg':'53',    'guifg':'White',   'guibg':'#5f005f' },
		\   { 'co': 256,    'ctermfg':'White',      'ctermbg':'90',    'guifg':'White',   'guibg':'#870087' },
		\   { 'co': 256,    'ctermfg':'Black',      'ctermbg':'133',   'guifg':'Black',   'guibg':'#af5faf' },
		\   { 'co': 16777216,                                          'guifg':'Black',   'guibg':'#c8a3d9' },
		\   { 'co': 16777216,                                          'guifg':'Black',   'guibg':'#fc97ef' },
		\   { 'co': 16,     'ctermbg':'Magenta',    'ctermfg':'Black', 'guibg':'#ffb3ff', 'guifg':'Black' },
		\   { 'co': 256,    'ctermfg':'White',      'ctermbg':'198',   'guifg':'White',   'guibg':'#ff0087' },
		\   { 'co': 256,    'ctermfg':'Black',      'ctermbg':'169',   'guifg':'Black',   'guibg':'#d75faf' },
		\   { 'co': 256,    'ctermfg':'Black',      'ctermbg':'204',   'guifg':'Black',   'guibg':'#ff5f87' },
		\   { 'co': 16777216,                                          'guifg':'Black',   'guibg':'#ff73bb' },
		\   { 'co': 16777216,                                          'guifg':'Black',   'guibg':'#ff8092' },
		\   { 'co': 256,    'ctermfg':'Black',      'ctermbg':'212',   'guifg':'Black',   'guibg':'#ff87d7' },
		\   { 'co': 256,    'ctermfg':'Black',      'ctermbg':'175',   'guifg':'Black',   'guibg':'#d787af' },
		\   { 'co': 256,    'ctermfg':'White',      'ctermbg':'96',    'guifg':'White',   'guibg':'#875f87' },
		\   { 'co': 256,    'ctermfg':'Black',      'ctermbg':'138',   'guifg':'Black',   'guibg':'#af8787' },
		\   { 'co': 256,    'ctermfg':'Black',      'ctermbg':'174',   'guifg':'Black',   'guibg':'#d78787' },
		\   { 'co': 256,    'ctermfg':'White',      'ctermbg':'95',    'guifg':'White',   'guibg':'#875f5f' },
		\   { 'co': 256,    'ctermfg':'White',      'ctermbg':'131',   'guifg':'White',   'guibg':'#af5f5f' },
		\]

	if ! has('gui_running')
		call filter(l:palette, 'v:val.co <= &t_Co')
	endif
	return map(l:palette, 'ingo#dict#Unlet(v:val, "co")')
endfunction

" vim: ts=4 sts=0 sw=4 noet
